import React from "react";
import { Card, CardContent } from "../ui/card";
import { SectionHeader } from "../shared/SectionHeader";
import { Lightbulb } from "lucide-react";

export function AIInsight({ reviewCount }: { reviewCount: number }) {
  return (
    <div className="mb-8">
      <SectionHeader title="Operational Insight" subtitle="Generated by Shura AI" />
      <Card className="bg-void-2 border-line">
        <CardContent className="p-6">
          <div className="flex gap-4">
            <div className="shrink-0 mt-1">
              <Lightbulb className="w-5 h-5 text-gold" />
            </div>
            <div>
              <p className="text-sm text-cream leading-relaxed">
                Review turnaround is optimal. The board has surfaced {reviewCount} complex cases
                that require your attention today. SHURA Core is actively monitoring patient trends
                across the active cohort.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
